#!/bin/sh

# this is the configure script I use. It represents most of the features I
# support and is a good baseline :)

./configure --prefix=/opt/rxvt --enable-utmp \
            --enable-wtmp --enable-lastlog --enable-xim --disable-strings --enable-xterm-scroll \
            --with-term=xterm --enable-keepscrolling --enable-xft \
            --enable-frills --disable-swapscreen \
            --with-codesets=eu,jp \
            --enable-cursor-blink --enable-pointer-blank --enable-cursor-blink
