#!/bin/sh

# this is the configure script I use. It represents most of the features I
# support and is a good baseline :)

./configure --prefix=/opt/rxvt --enable-utmp \
            --enable-wtmp --enable-lastlog --enable-xim --disable-strings \
            --with-term=rxvt --disable-keepscrolling --enable-xft --enable-mousewheel \
            --with-name=rxvt --enable-selectionscrolling --enable-pointer-blank \
            --enable-frills --enable-swapscreen --enable-transparency --enable-slipwheeling \
            --with-codesets=eu,jp --enable-menubar --enable-tinting \
            --enable-cursor-blink --enable-text-blink --enable-fading \
            --enable-plain-scroll --enable-rxvt-scroll --enable-combining \
            "$@"
