#! perl

# Copyright (C) 2011 Ryan Kavanagh <ryanakca@kubuntu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#:META:RESOURCE:%:string:the shell snippet to execute

=head1 NAME

bell-command - execute a command when the bell rings

=head1 DESCRIPTION

Runs the command specified by the C<URxvt.bell-command> resource when
a bell event occurs. For example, the following pops up a notification
bubble with the text "Beep, Beep" using notify-send:

   URxvt.bell-command: notify-send "Beep, Beep"

=cut

sub on_start {
   my ($self) = @_;

   $self->{bell_cmd} = $self->x_resource ("bell-command");

   ()
}

sub on_bell {
   my ($self) = @_;

   if (defined $self->{bell_cmd}) {
      $self->exec_async ($self->{bell_cmd});
   }

   ()
}
