#! perl

# this creates a simple digital clock

sub on_start {
   my ($self) = @_;

   $self->{overlay} = $self->overlay (-1, 0, 8, 1, urxvt::OVERLAY_RSTYLE, 0);
   $self->{timer} = urxvt::timer
                    ->new
                    ->start (1 + int urxvt::NOW) # make sure we update "on" the second
                    ->interval (1)
                    ->cb (sub {
                       $self->{overlay}->set (0, 0,
                          sprintf "%2d:%02d:%02d", (localtime urxvt::NOW)[2,1,0]);
                    });

   ()
}


