#! perl

# this creates a simple digital clock

sub on_init {
   my ($self) = @_;

   $self->{digital_clock_overlay} = $self->overlay (-1, 0, 8, 1, urxvt::OVERLAY_RSTYLE, 0);
   $self->{digital_clock_timer} = urxvt::timer
                    ->new
                    ->interval (1)
                    ->cb (sub {
                       $self->{digital_clock_overlay}->set (0, 0,
                          sprintf "%2d:%02d:%02d", (localtime urxvt::NOW)[2,1,0]);
                    });

   ()
}


