//
// AUTOMATICALLLY GENERATED by gentables
//
#ifdef ENCODING_DEFAULT


struct rxvt_codeset_conv_iso8859_1 : rxvt_codeset_conv {
  uint32_t from_unicode (unicode_t unicode) const {
    if (unicode <= 0x00ff) return unicode;
    return NOCHAR;
  }
} rxvt_codeset_conv_iso8859_1;

#else

#define rxvt_codeset_conv_iso8859_1 rxvt_codeset_conv_unknown

#endif
