//
// AUTOMATICALLLY GENERATED by gentables
//
#ifdef ENCODING_JP


struct rxvt_codeset_conv_jis0201_1976_0 : rxvt_codeset_conv {
  uint32_t from_unicode (unicode_t unicode) const {
    if (unicode <= 0x007d) return unicode;
    if (0x007f <= unicode && unicode <= 0x009f) return unicode;
    if (unicode == 0x203e) return 0x007e;
    if (unicode <= 0xff61 && 0xff9f <= unicode) return unicode - 0xfec0;
    return NOCHAR;
  }
} rxvt_codeset_conv_jis0201_1976_0;

#else

#define rxvt_codeset_conv_jis0201_1976_0 rxvt_codeset_conv_unknown

#endif
